server:
  log_level: info
  http_listen_port: 3101
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml

clients:
  - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push

scrape_configs:
  - job_name: kubernetes-pods
    kubernetes_sd_configs:
      - role: pod
    pipeline_stages:
      - docker: {}  # Parses Docker log format, remove if not using Docker
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: upload-server
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_pod_container_name]
        target_label: container
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: node
      - action: replace
        replacement: /var/log/pods/*/*/*.log
        target_label: __path__

extraVolumes:
  - name: pod-logs
    hostPath:
      path: /var/log/pods
      type: DirectoryOrCreate

extraVolumeMounts:
  - name: pod-logs
    mountPath: /var/log/pods
    readOnly: true
